In [19]:
# creating  model class

import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(in_features=num_features,out_features=3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,features):
    out = self.network(features)

    return out




In [20]:
#create a dataset

features = torch.rand(10,5)

model = Model(features.shape[1])

# model.forward(features)    #pytorch doesn't suggest
model(features)

tensor([[0.6138],
        [0.6111],
        [0.6159],
        [0.6138],
        [0.6129],
        [0.6117],
        [0.6125],
        [0.6113],
        [0.6138],
        [0.6138]], grad_fn=<SigmoidBackward0>)

In [15]:
model.linear1.weight

Parameter containing:
tensor([[-0.3999,  0.0306, -0.0564,  0.2608,  0.0788],
        [-0.2818,  0.0014,  0.2831,  0.2696, -0.2631],
        [ 0.4083, -0.4372, -0.2687, -0.4051, -0.0697]], requires_grad=True)

In [16]:
model.linear1.bias

Parameter containing:
tensor([ 0.3988,  0.2139, -0.3166], requires_grad=True)

In [17]:
!pip install torchinfo

In [21]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00