In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [4]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [6]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
X_train

array([[-0.07209134,  1.14181626, -0.10627121, ..., -0.76138745,
        -0.36862102, -1.12170946],
       [ 0.60182412, -0.30341872,  0.65189457, ...,  1.12762114,
         2.25061788,  2.18897257],
       [-0.55062795, -0.05314034, -0.59419154, ..., -0.91405744,
        -0.01493412, -0.15092868],
       ...,
       [-1.17725607, -0.84323485, -1.15521779, ..., -0.69778751,
        -0.63103388,  0.46944542],
       [-0.59876477, -0.18809437, -0.56708486, ...,  0.03346107,
         0.82772083,  0.00444033],
       [-0.73468049, -1.02971678, -0.72274295, ..., -0.7327524 ,
        -1.7572903 , -0.51235444]])

In [8]:
y_train

243    B
34     M
346    B
121    M
568    B
      ..
566    M
525    B
524    B
216    B
183    B
Name: diagnosis, Length: 455, dtype: object

In [9]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [10]:
y_train

array([1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,

In [10]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [11]:
X_train_tensor.shape

torch.Size([455, 30])

In [12]:
y_train_tensor.shape

torch.Size([455])

# Defining the model

In [13]:
import torch.nn as nn

In [26]:
class MySimpleNN(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out




# Important Parameter

In [15]:
lr = 0.1
epochs = 25

In [27]:
# defining the loss function
loss_function = nn.BCELoss()

# Training Pipeline

In [33]:
model = MySimpleNN(X_train_tensor.shape[1])


# define optimizer
optimizer = torch.optim.SGD(model.parameters(),lr=lr)

for epoch in range(epochs):
  # forward pass
  y_pred = model(X_train_tensor)


  # loss calculate
  loss = loss_function(y_pred,y_train_tensor.view(-1,1))

  #clear gradient
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  #upading parameter
  optimizer.step()


  print(f'Epochs:{epoch + 1}, Loss:{loss.item()}')


Epochs:1, Loss:0.5831172466278076
Epochs:2, Loss:0.48470357060432434
Epochs:3, Loss:0.42396652698516846
Epochs:4, Loss:0.3818691670894623
Epochs:5, Loss:0.35052886605262756
Epochs:6, Loss:0.3260612189769745
Epochs:7, Loss:0.3062947392463684
Epochs:8, Loss:0.2899065911769867
Epochs:9, Loss:0.2760394215583801
Epochs:10, Loss:0.26411065459251404
Epochs:11, Loss:0.2537093758583069
Epochs:12, Loss:0.24453680217266083
Epochs:13, Loss:0.23636984825134277
Epochs:14, Loss:0.22903838753700256
Epochs:15, Loss:0.2224101573228836
Epochs:16, Loss:0.21638070046901703
Epochs:17, Loss:0.21086613833904266
Epochs:18, Loss:0.20579838752746582
Epochs:19, Loss:0.20112140476703644
Epochs:20, Loss:0.19678868353366852
Epochs:21, Loss:0.19276106357574463
Epochs:22, Loss:0.1890055239200592
Epochs:23, Loss:0.18549375236034393
Epochs:24, Loss:0.18220154941082
Epochs:25, Loss:0.17910775542259216


In [34]:
model.linear.weight

Parameter containing:
tensor([[ 0.3814,  0.1099,  0.0896,  0.2819,  0.1271,  0.1745,  0.2153,  0.1833,
          0.0584, -0.0415,  0.0953,  0.0726,  0.0387,  0.0897,  0.0907, -0.1409,
         -0.0082,  0.1025,  0.0926, -0.0027,  0.4002,  0.2583,  0.3584,  0.4206,
          0.0700,  0.1846,  0.2441,  0.1417,  0.1823,  0.0616]],
       requires_grad=True)

# Evaluate


In [38]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5221606492996216
