In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [ ]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[-1.00461264,  0.22827485, -0.96049575, ..., -0.47201241,
        -0.47523507,  0.18663512],
       [-0.13012772, -0.33901876, -0.17969309, ..., -0.8696344 ,
        -0.88675196, -0.80944557],
       [ 0.0718985 , -0.96349923,  0.06561817, ...,  0.6664713 ,
        -0.33644898, -0.41443787],
       ...,
       [-0.04354505, -0.78050129, -0.1100834 , ..., -0.64871618,
        -0.28158006, -0.67954767],
       [-0.24557127, -0.80795098, -0.24804477, ...,  0.8343938 ,
         1.01268092,  1.04809434],
       [-0.5745854 , -0.9566368 , -0.60364126, ..., -0.94096294,
        -0.38486273, -0.25029417]])

In [ ]:
y_train

269    B
149    B
148    B
42     M
412    B
      ..
140    B
515    B
437    B
81     B
324    B
Name: diagnosis, Length: 455, dtype: object

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_train_tensor.shape

torch.Size([455])

# Defining the model

In [ ]:
class MySimpleNeuralNetwork:
  def __init__(self,X):
    self.weights = torch.rand(X.shape[1],1,dtype = torch.float64,requires_grad=True)
    self.bias = torch.zeros(1,dtype = torch.float64,requires_grad = True)

  def forward(self,X):
    z = torch.matmul(X,self.weights) + self.bias
    y_pred  = torch.sigmoid(z)
    return y_pred

  def loss_function(self,y_pred,y):
    # clamping prediction to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred,epsilon,1-epsilon)

    loss = -(y_train_tensor * torch.log(y_pred) + (1-y_train_tensor) * torch.log(1- y_pred)).mean()
    return loss



# Important Parameter

In [ ]:
lr = 0.1
epochs = 25

# Training Pipeline

In [ ]:
model = MySimpleNeuralNetwork(X_train_tensor)


for epoch in range(epochs):
  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred,y_train_tensor)


  # backward pass
  loss.backward()

  #upading parameter
  with torch.no_grad():
    model.weights -= lr * model.weights.grad
    model.bias -= lr * model.bias.grad


  model.weights.grad.zero_()
  model.bias.grad.zero_()


  print(f'Epochs:{epoch + 1}, Loss:{loss.item()}')


Epochs:1, Loss:3.533604126378669
Epochs:2, Loss:3.395190013823653
Epochs:3, Loss:3.2517226021041945
Epochs:4, Loss:3.1056144333589573
Epochs:5, Loss:2.957756742444681
Epochs:6, Loss:2.810509299475274
Epochs:7, Loss:2.657482180615708
Epochs:8, Loss:2.5051989730558217
Epochs:9, Loss:2.351388941107836
Epochs:10, Loss:2.1980256671597087
Epochs:11, Loss:2.0440558469488206
Epochs:12, Loss:1.893484120618246
Epochs:13, Loss:1.7432385534502017
Epochs:14, Loss:1.6005297786217532
Epochs:15, Loss:1.46766327223389
Epochs:16, Loss:1.3456938271876728
Epochs:17, Loss:1.238192836920729
Epochs:18, Loss:1.1459304347095753
Epochs:19, Loss:1.0675914152545594
Epochs:20, Loss:1.0024623572052918
Epochs:21, Loss:0.9503625384746982
Epochs:22, Loss:0.9091146198615015
Epochs:23, Loss:0.8764949752545311
Epochs:24, Loss:0.850517869703494
Epochs:25, Loss:0.829554342795823


In [ ]:
model.weights

tensor([[ 0.2104],
        [ 0.0090],
        [-0.2522],
        [-0.1653],
        [ 0.2192],
        [-0.1614],
        [-0.3370],
        [ 0.1555],
        [ 0.3196],
        [-0.1972],
        [-0.0149],
        [ 0.1022],
        [ 0.1593],
        [ 0.1448],
        [-0.1714],
        [-0.0922],
        [ 0.4401],
        [ 0.3552],
        [ 0.3913],
        [ 0.3801],
        [ 0.1021],
        [-0.0319],
        [-0.3165],
        [ 0.2835],
        [-0.1523],
        [ 0.1388],
        [-0.4110],
        [-0.2440],
        [ 0.2610],
        [ 0.1927]], dtype=torch.float64, requires_grad=True)

# Evaluate


In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.671283483505249
